### ISSUE TITLE
MongoDB Bad Auth Authentication Failed

### ISSUE THREAD

**Issue by cosmicfugues** [Sank6/Discord-Bot-List#109]
I create database access user and whitelisted all IP's. After i press connect button and select "Connect your application". I copy my link and replace password - database name.

This my database name right?
![Ekran Alıntısı](https://user-images.githubusercontent.com/55662450/88164430-cbe2a400-cc1c-11ea-9846-83e5def2571e.JPG)

C:\Users\Sponsor\Desktop\test\Discord-Bot-List>node src/index.js
(node:4848) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: bad
auth Authentication failed.
    at new MongooseServerSelectionError (C:\Users\Sponsor\Desktop\test\Discord-B
ot-List\node_modules\mongoose\lib\error\serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (C:\Users\Sponsor\Desktop\test\Discor
d-Bot-List\node_modules\mongoose\lib\connection.js:823:32)
    at Mongoose.connect (C:\Users\Sponsor\Desktop\test\Discord-Bot-List\node_mod
ules\mongoose\lib\index.js:333:15)
    at C:\Users\Sponsor\Desktop\test\Discord-Bot-List\src\index.js:12:20
    at Object.<anonymous> (C:\Users\Sponsor\Desktop\test\Discord-Bot-List\src\in
dex.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:71:12)
    at internal/main/run_main_module.js:17:47
(node:4848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:4848) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by cosmicfugues** [comment]
Solved, where is admin panel?

**Comment by Misly16** [comment]
What do you mean by admin panel, there is non

**Comment by cosmicfugues** [comment]
I mean how can i apply or decline bot?

22 Tem 2020 Çar 18:13 tarihinde Misly <notifications@github.com> şunu yazdı:

**Comment by Sank6** [comment]
Use the discord bot's commands.
