### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by MaximilianGT500** [Sank6/Discord-Bot-List#113]
(node:775) UnhandledPromiseRejectionWarning: MongoParseError: Invalid connection string
    at parseConnectionString (/var/www/html/dcbl/node_modules/mongodb/lib/core/uri_parser.js:547:21)
    at connect (/var/www/html/dcbl/node_modules/mongodb/lib/operations/connect.js:277:3)
    at cb (/var/www/html/dcbl/node_modules/mongodb/lib/mongo_client.js:222:5)
    at maybePromise (/var/www/html/dcbl/node_modules/mongodb/lib/utils.js:662:3)
    at MongoClient.connect (/var/www/html/dcbl/node_modules/mongodb/lib/mongo_client.js:218:10)
    at Promise (/var/www/html/dcbl/node_modules/mongoose/lib/connection.js:713:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/var/www/html/dcbl/node_modules/mongoose/lib/connection.js:710:19)
    at Mongoose.connect (/var/www/html/dcbl/node_modules/mongoose/lib/index.js:335:15)
    at /var/www/html/dcbl/src/index.js:12:20
    at Object.<anonymous> (/var/www/html/dcbl/src/index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Zaid-maker** [comment]
Becaus you dont encode your password in the connection  string

**Comment by MaximilianGT500** [comment]
How can encode my passwort?

**Comment by MaximilianGT500** [comment]
Ok it running the Cluster was Offline
