### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ByL4net** [Sank6/Discord-Bot-List#115]
What do I have to do with this error on the console

 .add(8, ({ c, author }) => process.env.ADMIN_USERS.split(' ').includes(author.id));
   ^
TypeError: Client.defaultPermissionLevels.add is not a function
at Object.<anonymous> (/app/src/bot/index.js:4:4)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/src/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

**Comment by Zaid-maker** [comment]
Because you don't put admin if or the bot don't have read perms in the server

**Comment by Sank6** [comment]
Check your `klasa` installation version is correct - [v0.5.0](https://github.com/dirigeants/klasa/tree/v0.5.0)
