### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by MaximilianGT500** [Sank6/Discord-Bot-List#196]
Cannot read property 'id' of undefined
    at eval (eval at wrap (/rbd/pnpm-volume/ae94be9f-dd67-4548-8a7d-cd422247bd65/node_modules/.registry.npmjs.org/pug-runtime/3.0.0/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:101:67)
    at template (eval at wrap (/rbd/pnpm-volume/ae94be9f-dd67-4548-8a7d-cd422247bd65/node_modules/.registry.npmjs.org/pug-runtime/3.0.0/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:202:7)
    at Object.exports.renderFile (/rbd/pnpm-volume/ae94be9f-dd67-XMR:452:38)
    at Object.exports.renderFile (/rbd/pnpm-volume/ae94be9f-dd67-XMR:442:21)
    at View.exports.__express [as engine] (/rbd/pnpm-volume/ae94be9f-dd67-XMR:491:11)
    at View.render (/rbd/pnpm-volume/ae94be9f-dd67-XMR/view.js:135:8)
    at tryRender (/rbd/pnpm-volume/ae94be9f-dd67-XMR/application.js:640:10)
    at Function.render (/rbd/pnpm-volume/ae94be9f-dd67-XMR/application.js:592:3)
    at ServerResponse.render (/rbd/pnpm-volume/ae94be9f-dd67-XMR/response.js:1012:7)

**Comment by discord-bot-purchases** [comment]
already made #191

**Comment by Sank6** [comment]
Fixed
