### ISSUE TITLE
Submit Bug

### ISSUE THREAD

**Issue by WinstoneDev** [Sank6/Discord-Bot-List#199]
[2020-09-06 19:03:48] [EVENT] /root/Discord-Winstone/DBL/node_modules/klasa/src/events/unhandledRejection.js
[2020-09-06 19:03:48] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2020-09-06 19:03:48]   "TypeError: Cannot read property 'state' of null\n" +
[2020-09-06 19:03:48]   '    at /root/Discord-Winstone/DBL/src/routes/api/bots/submit.js:45:30\n' +
[2020-09-06 19:03:48]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
[2020-09-06 19:03:48]     at KlasaClient.emit (events.js:303:17)
[2020-09-06 19:03:48]     at module.exports.run (/root/Discord-Winstone/DBL/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-09-06 19:03:48]     at module.exports._run (/root/Discord-Winstone/DBL/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2020-09-06 19:03:48]     at process.emit (events.js:314:20)
[2020-09-06 19:03:48]     at processPromiseRejections (internal/process/promises.js:245:33)
[2020-09-06 19:03:48]     at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by Sank6** [comment]
Does this still happen? I just pushed a bunch of commits.

**Comment by WinstoneDev** [comment]
I look if the error still happen

**Comment by WinstoneDev** [comment]
[2020-09-06 20:31:34] [EVENT] /root/Discord-Winstone/DBL/node_modules/klasa/src/events/unhandledRejection.js
[2020-09-06 20:31:34] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2020-09-06 20:31:34]   'ReferenceError: bot is not defined\n' +
[2020-09-06 20:31:34]   '    at /root/Discord-Winstone/DBL/src/routes/api/bots/submit.js:62:23\n' +
[2020-09-06 20:31:34]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
[2020-09-06 20:31:34]     at KlasaClient.emit (events.js:303:17)
[2020-09-06 20:31:34]     at module.exports.run (/root/Discord-Winstone/DBL/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-09-06 20:31:34]     at module.exports._run (/root/Discord-Winstone/DBL/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2020-09-06 20:31:34]     at process.emit (events.js:314:20)
[2020-09-06 20:31:34]     at processPromiseRejections (internal/process/promises.js:245:33)
[2020-09-06 20:31:34]     at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by thedev2307** [comment]
try to reinstall all packages, maybe it work lol
