### ISSUE TITLE
BOT not working

### ISSUE THREAD

**Issue by MaximilianGT500** [Sank6/Discord-Bot-List#206]
Log: 

[2020-09-08 13:45:XMRorg/klasa/0.5.0/node_modules/klasa/src/events/unhandledRejection.js
[2020-09-08 13:45:XMRBOTs validation failed: username: ' +
[2020-09-08 13:45:42]   'Path `username` is required.\n    at model.Document.invalidate ' +
[2020-09-08 13:45:XMRmongoose/5.10.3/node_modules/mongoose/lib/document.js:2598:32)\n' +
[2020-09-08 13:45:42]   '    at ' +
[2020-09-08 13:45:42]   '/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/mongoose/5.10.3/node_modules/mongoose/lib/document.js:2418:17\n' +
[2020-09-08 13:45:42]   '    at ' +
[2020-09-08 13:45:42]   '/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/mongoose/5.10.3/node_modules/mongoose/lib/schematype.js:1222:9\n' +
[2020-09-08 13:45:42]   '    at processTicksAndRejections (internal/process/task_queues.js:81:9)')
[2020-09-08 13:45:42]     at KlasaClient.emit (events.js:185:17)
[2020-09-08 13:45:42]     at module.exports.run (/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/klasa/0.5.0/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-09-08 13:45:42]     at module.exports._run (/rbd/pnpm-volume/60b0f3c8-dc4e-XMRstructures/Event.js:101:15)
[2020-09-08 13:45:42]     at process.emit (events.js:196:13)
[2020-09-08 13:45:42]     at processPromiseRejections (internal/process/promises.js:165:18)
[2020-09-08 13:45:42]     at processTicksAndRejections (internal/process/task_queues.js:89:32)

**Comment by MaximilianGT500** [comment]
Log 2:

[2020-09-08 13:50:49] [COMMAND] /app/src/bot/commands/Bots/verify.js
[2020-09-08 13:50:49] TypeError: Cannot read property 'botid' of null
[2020-09-08 13:50:49]     at module.exports.run (/app/src/bot/commands/Bots/verify.js:24:40)
[2020-09-08 13:50:49]     at processTicksAndRejections (internal/process/task_queues.js:88:5)
[2020-09-08 13:50:49]     at async module.exports.runCommand (/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/klasa/0.5.0/node_modules/klasa/src/monitors/commandHandler.js:34:23)
[2020-09-08 13:50:49]     at async module.exports._run (/rbd/pnpm-volume/60b0f3c8-dc4e-XMRstructures/Monitor.js:99:4)
[2020-09-08 13:51:XMRorg/klasa/0.5.0/node_modules/klasa/src/events/unhandledRejection.js
[2020-09-08 13:51:XMRBOTs validation failed: username: ' +
[2020-09-08 13:51:49]   'Path `username` is required.\n    at model.Document.invalidate ' +
[2020-09-08 13:51:XMRmongoose/5.10.3/node_modules/mongoose/lib/document.js:2598:32)\n' +
[2020-09-08 13:51:49]   '    at ' +
[2020-09-08 13:51:49]   '/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/mongoose/5.10.3/node_modules/mongoose/lib/document.js:2418:17\n' +
[2020-09-08 13:51:49]   '    at ' +
[2020-09-08 13:51:49]   '/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/mongoose/5.10.3/node_modules/mongoose/lib/schematype.js:1222:9\n' +
[2020-09-08 13:51:49]   '    at processTicksAndRejections (internal/process/task_queues.js:81:9)')
[2020-09-08 13:51:49]     at KlasaClient.emit (events.js:185:17)
[2020-09-08 13:51:49]     at module.exports.run (/rbd/pnpm-volume/60b0f3c8-dc4e-4878-8b17-506f47f58ace/node_modules/.registry.npmjs.org/klasa/0.5.0/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-09-08 13:51:49]     at module.exports._run (/rbd/pnpm-volume/60b0f3c8-dc4e-XMRstructures/Event.js:101:15)
[2020-09-08 13:51:49]     at process.emit (events.js:196:13)
[2020-09-08 13:51:49]     at processPromiseRejections (internal/process/promises.js:165:18)
[2020-09-08 13:51:49]     at processTicksAndRejections (internal/process/task_queues.js:89:32)

**Comment by D3monSlayer64** [comment]
fix it yourself

**Comment by MaximilianGT500** [comment]
Fixed

**Comment by D3monSlayer64** [comment]
@MaximilianGT500 How?

**Comment by MaximilianGT500** [comment]
Reset the Database and add two different bots - works for me
