### ISSUE TITLE
Submit not working

### ISSUE THREAD

**Issue by Sparkot49** [Sank6/Discord-Bot-List#207]
When i submit my bot i have error message 

[2020-09-08 13:51:38] [EVENT] /srv/DiscordListe/node_modules/klasa/src/events/unhandledRejection.js
[2020-09-08 13:51:38] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2020-09-08 13:51:38]   'ReferenceError: bot is not defined\n' +
[2020-09-08 13:51:38]   '    at /srv/DiscordListe/src/routes/api/bots/submit.js:62:23\n' +
[2020-09-08 13:51:38]   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)')
[2020-09-08 13:51:38]     at KlasaClient.emit (events.js:304:17)
[2020-09-08 13:51:38]     at module.exports.run (/srv/DiscordListe/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-09-08 13:51:38]     at module.exports._run (/srv/DiscordListe/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2020-09-08 13:51:38]     at process.emit (events.js:315:20)
[2020-09-08 13:51:38]     at processPromiseRejections (internal/process/promises.js:209:33)
[2020-09-08 13:51:38]     at processTicksAndRejections (internal/process/task_queues.js:98:32)

**Comment by Sank6** [comment]
Fixed
