### ISSUE TITLE
  code: 'MODULE_NOT_FOUND',

### ISSUE THREAD

**Issue by Naiym223** [Sank6/Discord-Bot-List#227]
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'module-alias/register'
Require stack:
- C:\Users\prest\OneDrive\Desktop\discord-bot-client-master\Discord-Bot-List\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\prest\OneDrive\Desktop\discord-bot-client-master\Discord-Bot-List\src\index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\prest\\OneDrive\\Desktop\\discord-bot-client-master\\Discord-Bot-List\\src\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discordbotlist@3.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discordbotlist@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prest\AppData\Roaming\npm-cache\_logs\2020-09-16T15_07_47_662Z-debug.log

**Comment by Sank6** [comment]
Install modules? Read the wiki setup.
