### ISSUE TITLE
Unknown Error and members not defined

### ISSUE THREAD

**Issue by EggyOnCrack** [Sank6/Discord-Bot-List#312]
error 1: ![image](https://user-images.githubusercontent.com/69737561/97796842-cc5af400-1c7b-11eb-9136-b2c4a390c6ac.png)

error 2: 
![image](https://user-images.githubusercontent.com/69737561/97796847-dd0b6a00-1c7b-11eb-8003-c037db9f134f.png)

**Comment by Sank6** [comment]
Check your config file is correct for the second error. I don't know why you're getting unknown error though. I'll have a look.

**Comment by shootdot** [comment]
@Sank6 This error is occured by the owners field 

```
TypeError: Cannot read property 'owners' of null
     at module.exports (/root/dis3/src/utils/checkFields.js:48:20)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /root/dis3/src/routes/api/bots/submit.js:39:17
 TypeError: Cannot destructure property 'bot' of 'check' as it is undefined.
     at /root/dis3/src/routes/api/bots/submit.js:45:10
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
 [EVENT] /root/dis3/node_modules/klasa/src/events/unhandledRejection.js
 Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
   "TypeError: Cannot destructure property 'bot' of 'check' as it is undefined.\n" +
   '    at /root/dis3/src/routes/api/bots/submit.js:45:10\n' +
   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
    at KlasaClient.emit (events.js:303:17)
     at module.exports.run (/root/dis3/node_modules/klasa/src/events/unhandledRejection.js:12:15)
     at module.exports._run (/root/dis3/node_modules/klasa/src/lib/structures/Event.js:101:15)
     at process.emit (events.js:326:22)
     at processPromiseRejections (internal/process/promises.js:245:33)
     at processTicksAndRejections (internal/process/task_queues.js:94:32)

```

**Comment by yuu0007** [comment]
i am also getting the first error @Sank6

**Comment by shootdot** [comment]
Till Sank6 Updates I have fixed the bug
Goto util/checkFields.js and replace with this code

```
const recaptcha2 = require('recaptcha2')
const is = require('is-html');

const { getBot } = require('@utils/discordApi');

const { server: {id}, bot_options: {max_owners_count}, web: {recaptcha_v2: {site_key, secret_key}} } = require("@root/config.json");

const recaptcha = new recaptcha2({
    siteKey: site_key,
    secretKey: secret_key
})

module.exports = async (req, b) => {
    let data = req.body;

    if (!data.recaptcha_token)
        return {success: false, message: "Invalid Captcha"}

    try {
        await recaptcha.validate(data.recaptcha_token)
    } catch (e) {
        return {success: false, message: "Invalid Captcha"}
    }

    if (data.description.length > 120) return {success: false, message: "Your summary is too long."};
    
    let memberCheck = await req.app.get('client').guilds.cache.get(id).members.fetch(req.user.id);

    let [bot] = await getBot(req.params.id);
    if (memberCheck == null) {
        return {success: false, message: "You aren't in the server", button: {text: "Join", url: "/join"}}
    }
    if (bot.user_id && bot.user_id[0].endsWith("is not snowflake."))
        return {success: false, message: "Invalid bot id"}
    if (bot.message == "Unknown User" || bot.bot !== true)
        return {success: false, message: "Invalid bot id"}
    if (is(data.description))
        return {success: false, message: "HTML is not supported in your bot summary"}
    if (!data.long.length || !data.description.length || !data.prefix.length)
        return {success: false, message: "Invalid submission. Check you filled all the fields."}

    if (b && !b.owners.includes(req.user.id) && !server.admin_user_ids.includes(req.user.id))
        return {success: false, message: "Invalid request. Please sign in again.", button: {text: "Logout", url: "/logout"}}

    if (b && data.owners.replace(',', '').split(' ').remove('').join() !== b.owners.slice(1).join() && b.owners[0] !== req.user.id)
        return {success: false, message: "Only the primary owner can edit additional owners"};
    let users = [req.user.id];
    if (!data.owners) {} else {
    users = users.concat(data.owners.replaceAll(',', '').split('  ').remove(''));
    }
    //users = users.filter(id => /[0-9]{16,20}/g.test(id))

    try {
        users = await req.app.get('client').guilds.cache.get(id).members.fetch({user: users});
        users = [...new Set(users.map(x => { return x.user }).filter(user => !user.bot).map(u => u.id))];

        if (users.length > max_owners_count)
            return {success: false, message: `You can only add up to ${max_owners_count - 1} additional owners`};

        return {success: true, bot, users}
    } catch(e) {
        return {success: false, message: "Invalid Owner IDs"};
    }
}
```

**Comment by Zaid-maker** [comment]
Instead of telling like this please make the pill request with the changes

**Comment by shootdot** [comment]
It still may contain bug but I fixed the submit issue so I thought why to make a pull request which contains a bugs 😂

**Comment by Zaid-maker** [comment]
Nice tho

**Comment by Sank6** [comment]
No, don't do that. That means you can change the primary owner. Also whats with `if (!data.owners) {} else {` ?
I think the new commit should fix it. Reopen this if it's still open.
