### ISSUE TITLE
How do I add searchbar in the home page?

### ISSUE THREAD

**Issue by lavv6** [Sank6/Discord-Bot-List#387]
I've tried it with this code:

```         h1 Search
            p
                span.strikethrough Just another bot list for Discord.
        br
        .input-holder
            input#searchbar.input(type='text' placeholder=' ')
            .placeholder Search
        #cards
            if (cards.length == 0)
                p No bots found. Try searching for something else.
            else
                each card in cards
                    div.card
                        img.icon(src=card.logo)
                        h2.title #{card.username}
                            a.likes(href=`/bots/like/${card.botid}`)
                                i.far.fa-heart
                                | #{card.likes || 0}
                        p.desc #{card.description}
                        a.small.button(href=`/bots/${card.botid}`) View bot info
        br
    script.
        const node = document.getElementById("searchbar");
        node.addEventListener("keyup", function(event) {
        if (event.key === "Enter") {
        location.href = `/bots/search/?q=${node.value}`
        }
        });```


But it doesn't work.

**Comment by Sank6** [comment]
Try this:
```pug
br
        .input-holder
            input#searchbar.input(type='text' placeholder=' ')
            .placeholder Search
script
        const node = document.getElementById("searchbar");
        node.addEventListener("keyup", function(event) {
                if (event.key === "Enter") {
                        location.href = `/bots/search/?q=${node.value}`
                }
        });
```

**Comment by lavv6** [comment]
I did this: 

```doctype html
include includes/head.pug
body(onload="load()")
    include includes/nav.pug
    #content
    
       
        span.header
           
        
            h3 <i class="fas fa-angle-up fa-1x"></i> Top Voted Discord Bots
            p These are the top voted bots this month!
        #searchMore
            | Would you like to 
            a(href='/bots/search/') search all bots
        #cards
            span#loading Loading...
            
            br
        .input-holder
            input#searchbar.input(type='text' placeholder=' ')
            .placeholder Search
script
        const node = document.getElementById("searchbar");
        node.addEventListener("keyup", function(event) {
                if (event.key === "Enter") {
                        location.href = `/bots/search/?q=${node.value}`
                }
        });
            
            ```

and it shows this error: 

```SyntaxError: Mismatched Bracket: )
    at Function.parseChar (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/character-parser/2.2.0/node_modules/character-parser/index.js:154:21)
    at Lexer.attributeValue (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1412:31)
    at Lexer.attribute (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1270:30)
    at Lexer.attrs (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1449:20)
    at Lexer.callLexerFunction (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1642:23)
    at Lexer.advance (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1681:12)
    at Lexer.callLexerFunction (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1642:23)
    at Lexer.getTokens (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:1701:12)
    at lex (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-lexer/5.0.0/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug/3.0.0/node_modules/pug/lib/index.js:104:9)
    at Function.loadString [as string] (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug-load/3.0.0/node_modules/pug-load/index.js:53:24)
    at compileBody (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug/3.0.0/node_modules/pug/lib/index.js:82:18)
    at Object.exports.compile (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug/3.0.0/node_modules/pug/lib/index.js:267:16)
    at handleTemplateCache (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug/3.0.0/node_modules/pug/lib/index.js:240:25)
    at Object.exports.renderFile (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug/3.0.0/node_modules/pug/lib/index.js:452:10)
    at Object.exports.renderFile (/rbd/pnpm-volume/ac00331f-8ad9-4ec0-8a1e-fa4ff375cd03/node_modules/.registry.npmjs.org/pug/3.0.0/node_modules/pug/lib/index.js:442:21)```

**Comment by lavv6** [comment]
??????

**Comment by Sank6** [comment]
I forgot the `.` after the `script`. Add it back in. Also, that error message is awful lol.
