### ISSUE TITLE
Bug: "Unknown Member" error if the user is not in the server

### ISSUE THREAD

**Issue by TheCuteFoxxy** [Sank6/Discord-Bot-List#402]
An error occurs when a user tries to visit the "add" page if they are not in the server, causing a 504 Gateway Timeout.

`[2020-12-17 00:34:05] [EVENT] /home/container/node_modules/klasa/src/events/unhandledRejection.js
[2020-12-17 00:34:05] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2020-12-17 00:34:05]   'DiscordAPIError: Unknown Member\n' +
[2020-12-17 00:34:05]   '    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:154:13)\n' +
[2020-12-17 00:34:05]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
[2020-12-17 00:34:05]   '    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:39:14)\n' +
[2020-12-17 00:34:05]   '    at async module.exports.auth (/home/container/src/utils/discordApi.js:9:20)')
[2020-12-17 00:34:05]     at KlasaClient.emit (events.js:304:17)
[2020-12-17 00:34:05]     at module.exports.run (/home/container/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-12-17 00:34:05]     at module.exports._run (/home/container/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2020-12-17 00:34:05]     at process.emit (events.js:315:20)
[2020-12-17 00:34:05]     at processPromiseRejections (internal/process/promises.js:245:33)
[2020-12-17 00:34:05]     at processTicksAndRejections (internal/process/task_queues.js:94:32)`

If there is a way to add a catch for this like to prompt the user to join the server, that would be helpful. If its not a major edit, I can just edit my files without doing a full PR.

**Comment by shootdot** [comment]
@TheCuteFoxxy I have fixed the issue. goto `src/utils/discordApi.js` and replace the code with this
```js
const fetch = require('node-fetch');

const { server: { role_ids: { bot_verifier } }, server: { admin_user_ids, id } } = require("@root/config.json")

module.exports.auth = async (req, res, next) => {
    if (!req.user) return res.redirect("/login");
    req.user.staff = false
    try {
        const member = await req.app.get('client').guilds.cache.get(id).members.fetch(req.user.id);
        if (admin_user_ids.includes(req.user.id) || member.roles.cache.has(bot_verifier)) req.user.staff = true
    }
    catch (e) {
        return next();
    }
    return next();
}

module.exports.getUser = async (user) => {
    let { accessToken } = user;

    user = await fetch(`https://discord.com/api/users/@me`, {
        headers: {
            Authorization: `Bearer ${accessToken}`
        }
    });

    user = await user.json();

    if (user.code === 0) return false;
    return user;
};
```

**Comment by Sank6** [comment]
👍 Looks good. I'll have a look and add it soon.

**Comment by Lucaslah** [comment]
Works for Me

**Comment by Sank6** [comment]
Added: e13f5f2
