### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LNTheLord** [Sank6/Discord-Bot-List#412]
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1299:21)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Function.listen (/rbd/pnpm-volume/575e6d42-7a29-4990-bec8-1bbeccb94418/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:618:24)
at /app/src/structures/app.js:43:50
    at new Promise (<anonymous>)
at App.listen (/app/src/structures/app.js:43:12)
at /app/src/index.js:19:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}

**Comment by shootdot** [comment]
Looks like your port `80` is running. Try switching to different port like `8080`
