### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Misly16** [Sank6/Discord-Bot-List#43]
im getting the following error 

/rbd/pnpm-volume/57323152-afee-4a56-a145-4c2ab10bea63/node_modules/klasa/src/lib/extensions/KlasaUserStore.js:7
class KlasaUserStore extends UserStore {
                             ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/rbd/pnpm-volume/57323152-afee-4a56-a145-4c2ab10bea63/node_modules/klasa/src/lib/extensions/KlasaUserStore.js:7:30)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/57323152-afee-4a56-a145-4c2ab10bea63/node_modules/klasa/src/lib/Client.js:25:24)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)

It might be to do with mongo as i dont know if i added the correct format of url

**Comment by SplitXPlayZ** [comment]
It's an issue with Klasa, contact the Klasa package owner of it.

**Comment by Misly16** [comment]
i asked in their discord and got this response from one of the developers. "klasa settings and sgn don't support discord.js stable". Is there anyway to make it work?

**Comment by Sank6** [comment]
Use discord.js master
