### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#434]
I did the stuff in the dev dashboard and it is not working. I get the incorrect OAuth2 URI error. My dev dashboard: 
![image](https://user-images.githubusercontent.com/76178542/103469162-369d1d00-4d2f-11eb-9bc4-a05bd9b22db6.png)

**Comment by shootdot** [comment]
Make sure in config.json your website URL is not ending with `/`. Also https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri

**Comment by legofan10** [comment]
> Make sure in config.json your website URL (`domain_with_protocol` Field) is not ending with `/`. Also https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri

still does not work

**Comment by shootdot** [comment]
@legofan10 Send screenshot of `config.json` from `web` part

**Comment by legofan10** [comment]
![Screenshot 2021-01-03 113502](https://user-images.githubusercontent.com/76178542/103483808-c8506d00-4db7-11eb-85b1-9ecf82d886b9.png)

**Comment by Sank6** [comment]
Your discord client id is different to the one in your first screenshot of the dev dashboard.

**Comment by legofan10** [comment]
> Your discord client id is different to the one in your first screenshot of the dev dashboard.

works thx

**Comment by legofan10** [comment]
> Your discord client id is different to the one in your first screenshot of the dev dashboard.

nope. does not now. shows code when you finish login: `TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)`
