### ISSUE TITLE
Login not working #2

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#441]
> Your discord client id is different to the one in your first screenshot of the dev dashboard.

nope. does not now. shows code when you finish login: `TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/773d9154-d2e6-4e68-be52-6551887b083e/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)`

_Originally posted by @legofan10 in https://github.com/Sank6/Discord-Bot-List/issues/434#issuecomment-753654776_

**Comment by legofan10** [comment]
nvm, my bot secret had invalid stuff. idk why
