### ISSUE TITLE
duplicate key error collection mongodb

### ISSUE THREAD

**Issue by gelones** [Sank6/Discord-Bot-List#458]
I was testing the repository until I found a problem, a person from like on the bot works perfectly, on mongodb a user table is created with the information, but if another person tries to vote for the bot, there is an error in the terminal that does not let the person to vote.

error:

`[EVENT] C:\Users\rogeria\Desktop\Discord-Bot-List-master\node_modules\klasa\src\events\unhandledRejection.js
[2021-01-11 19:44:38] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2021-01-11 19:44:38]   'MongoError: E11000 duplicate key error collection: 5f1f18d0815f2254d753c571_test.users index: botliked_1 dup key: { botliked: "708321561842079824" }\n' +
[2021-01-11 19:44:38]   '    at Function.create (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\core\\error.js:57:12)\n' +
[2021-01-11 19:44:38]   '    at toError (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\utils.js:123:22)\n' +
[2021-01-11 19:44:38]   '    at C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\operations\\common_functions.js:379:39\n' +
[2021-01-11 19:44:38]   '    at handler (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\core\\sdam\\topology.js:942:24)\n' +
[2021-01-11 19:44:38]   '    at C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\cmap\\connection_pool.js:350:13\n' +
[2021-01-11 19:44:38]   '    at handleOperationResult (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\core\\sdam\\server.js:558:5)\n' +
[2021-01-11 19:44:38]   '    at MessageStream.messageHandler (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\cmap\\connection.js:277:5)\n' +
[2021-01-11 19:44:38]   '    at MessageStream.emit (events.js:315:20)\n' +
[2021-01-11 19:44:38]   '    at processIncomingData (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:144:12)\n' +
[2021-01-11 19:44:38]   '    at MessageStream._write (C:\\Users\\rogeria\\Desktop\\Discord-Bot-List-master\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:42:5)\n' +
[2021-01-11 19:44:38]   '    at writeOrBuffer (internal/streams/writable.js:358:12)\n' +
[2021-01-11 19:44:38]   '    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n' +
[2021-01-11 19:44:38]   '    at TLSSocket.ondata (internal/streams/readable.js:719:22)\n' +
[2021-01-11 19:44:38]   '    at TLSSocket.emit (events.js:315:20)\n' +
[2021-01-11 19:44:38]   '    at addChunk (internal/streams/readable.js:309:12)\n' +
[2021-01-11 19:44:38]   '    at readableAddChunk (internal/streams/readable.js:284:9)')
[2021-01-11 19:44:38]     at KlasaClient.emit (events.js:304:17)
[2021-01-11 19:44:38]     at module.exports.run (C:\Users\rogeria\Desktop\Discord-Bot-List-master\node_modules\klasa\src\events\unhandledRejection.js:12:15)
[2021-01-11 19:44:38]     at module.exports._run (C:\Users\rogeria\Desktop\Discord-Bot-List-master\node_modules\klasa\src\lib\structures\Event.js:101:15)
[2021-01-11 19:44:38]     at process.emit (events.js:315:20)
[2021-01-11 19:44:38]     at processPromiseRejections (internal/process/promises.js:245:33)
[2021-01-11 19:44:38]     at processTicksAndRejections (internal/process/task_queues.js:94:32)`

**Comment by Sank6** [comment]
👍 Good issue but that's not the fix. I'll try and fix it in the development branch.

**Comment by Sank6** [comment]
Ok so the issue here is going to be MongoDB's index, which basically stores that the `botliked` field needs to be unique. Either use [`dropIndex("botliked")`](https://docs.mongodb.com/manual/reference/method/db.collection.dropIndex/), or edit the index in MongoDB compass / something similar. The fix above will work for a fresh new database with no previous indexing, so if you've only just being using your database for testing, just wipe it completely and it should work.
Hope that helps 👍
