### ISSUE TITLE
Search option doesn’t work 

### ISSUE THREAD

**Issue by biswajitguha01** [Sank6/Discord-Bot-List#471]
Search option not working help me how to fix it

**Comment by biswajitguha01** [comment]
`Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2021-01-18 17:48:38]   "TypeError: Cannot read property 'toLowerCase' of undefined\n" +
[2021-01-18 17:48:38]   '    at C:\\Users\\Administrator\\Desktop\\Discord-Bot-List New\\src\\routes\\bots\\search.js:13:26\n' +
[2021-01-18 17:48:38]   '    at Array.filter (<anonymous>)\n' +
[2021-01-18 17:48:38]   '    at C:\\Users\\Administrator\\Desktop\\Discord-Bot-List New\\src\\routes\\bots\\search.js:12:22\n' +
[2021-01-18 17:48:38]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
[2021-01-18 17:48:38]     at KlasaClient.emit (events.js:304:17)
[2021-01-18 17:48:38]     at module.exports.run (C:\Users\Administrator\Desktop\Discord-Bot-List New\node_modules\klasa\src\events\unhandledRejection.js:12:15)
[2021-01-18 17:48:38]     at module.exports._run (C:\Users\Administrator\Desktop\Discord-Bot-List New\node_modules\klasa\src\lib\structures\Event.js:101:15)
[2021-01-18 17:48:38]     at process.emit (events.js:315:20)
[2021-01-18 17:48:38]     at processPromiseRejections (internal/process/promises.js:245:33)
[2021-01-18 17:48:38]     at processTicksAndRejections (internal/process/task_queues.js:94:32)
[2021-01-18 17:51:25] [EVENT] C:\Users\Administrator\Desktop\Discord-Bot-List New\node_modules\klasa\src\events\unhandledRejection.js
[2021-01-18 17:51:25] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2021-01-18 17:51:25]   "TypeError: Cannot read property 'toLowerCase' of undefined\n" +
[2021-01-18 17:51:25]   '    at C:\\Users\\Administrator\\Desktop\\Discord-Bot-List New\\src\\routes\\bots\\search.js:13:26\n' +
[2021-01-18 17:51:25]   '    at Array.filter (<anonymous>)\n' +
[2021-01-18 17:51:25]   '    at C:\\Users\\Administrator\\Desktop\\Discord-Bot-List New\\src\\routes\\bots\\search.js:12:22\n' +
[2021-01-18 17:51:25]   '    at processTicksAndRejections (internal/process/task_queues.js:93:5)')
[2021-01-18 17:51:25]     at KlasaClient.emit (events.js:304:17)
[2021-01-18 17:51:25]     at module.exports.run (C:\Users\Administrator\Desktop\Discord-Bot-List New\node_modules\klasa\src\events\unhandledRejection.js:12:15)
[2021-01-18 17:51:25]     at module.exports._run (C:\Users\Administrator\Desktop\Discord-Bot-List New\node_modules\klasa\src\lib\structures\Event.js:101:15)
[2021-01-18 17:51:25]     at process.emit (events.js:315:20)
[2021-01-18 17:51:25]     at processPromiseRejections (internal/process/promises.js:245:33)
[2021-01-18 17:51:25]     at processTicksAndRejections (internal/process/task_queues.js:94:32) `

I got this error & bot get offline

**Comment by Sank6** [comment]
Are you on dev or master?

**Comment by biswajitguha01** [comment]
I am a dev

**Comment by Sank6** [comment]
That could be something to do with the last username update commit. I'll have a look.

**Comment by biswajitguha01** [comment]
Ok please resolve this, as soon as possible.

**Comment by Sank6** [comment]
I can't seem to find the issue with the username change, but I've added the search button on mobile.
Can you add a `console.log(JSON.stringify(bot))` inside the filter function on line 13 `src/routes/bots/search.js` and check the final bot logged before throwing the error.

**Comment by Sank6** [comment]
Fixed
