### ISSUE TITLE
it not working 

### ISSUE THREAD

**Issue by NevaehAnimeLover** [Sank6/Discord-Bot-List#483]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'module-alias/register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/Discord-Bot-List/src/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discordbotlist@3.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discordbotlist@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-06T08_30_19_986Z-debug.log
exit status 1

The authenticity of host 'github.com (140.82.114.3)' can't be established.a4d261
RSA key fingerprint is "token".
Are you sure you want to continue connecting (yes/no)? [..................] / rollb[..................] / rollbackFailedOptional: verb npm-session f963f04540a4d261

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information#setting-up
