### ISSUE TITLE
Im using repl

### ISSUE THREAD

**Issue by NevaehAnimeLover** [Sank6/Discord-Bot-List#484]
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@bot/index'
Require stack:
- /home/runner/DarkcyanImpishBackticks/Discord-Bot-List/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._resolveFilename (/home/runner/DarkcyanImpishBackticks/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/DarkcyanImpishBackticks/Discord-Bot-List/src/index.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/DarkcyanImpishBackticks/Discord-Bot-List/src/index.js'
  ]
}

**Comment by Sank6** [comment]
Module alias isn't working properly. If it doesn't work on the platform, use absolute paths.
