### ISSUE TITLE
search /bots/search not working?

### ISSUE THREAD

**Issue by ezywebca** [Sank6/Discord-Bot-List#490]
the link image on site the link for search that would point off to /bots/search to search bots does not work

**Comment by ezywebca** [comment]
@Sank6 any idea on how to fix this btw ?

**Comment by ezywebca** [comment]
sites over at https://www.dislister.ga

**Comment by Sank6** [comment]
Can you log this https://github.com/Sank6/Discord-Bot-List/issues/471#issuecomment-765341288

**Comment by ezywebca** [comment]
@Sank6 im confused as what you want me todo ive done this what would you like the output

**Comment by ezywebca** [comment]
im on plesk running this i cant console log this

**Comment by Sank6** [comment]
Are you on the dev branch or master?

**Comment by ezywebca** [comment]
@Sank6 master 
but this what i got for you
`{"owners":{"additional":[],"primary":"676195747904880690"},"ratelimit":{"time":"2021-02-17T20:57:23.739Z"},"state":"verified","tags":[],"nsfw":false,"likes":1,"username":"PartnerBot","botid":"805958622336778242","logo":"https://cdn.discordapp.com/avatars/805958622336778242/9e9b54e1f5c33dfe5e86ce76784d2c1e.png?size=256","description":"PartnerBot Is your #1 Server To Server Bot Bumper!","long":"<p><strong>PartnerBot is your #1 bot for server to server bumping!</strong><br />\n<br />\n<em><u><strong>How does I work?</strong></u></em></p>\n\n<ol>\n\t<li>Simply invite <strong>PartnerBot </strong>to your server!</li>\n\t<li>Create a channel for where all the <strong>PartnerBot </strong>bumps will go.</li>\n\t<li>Type <strong>p!help </strong>to get more help but from here type <strong>p!init #yourchannel </strong>this will set <strong>PartnerBots Bump Channel.</strong><br />\n\tFrom here type <strong>p!desc your servers description</strong></li>\n\t<li>Finally Dont Forget To <strong>p!bump</strong> your server every so often! </li>\n</ol>\n\n<p>Enjoy!</p>\n","prefix":"p!","note":"","servers":null,"github":"","invite":"https://discordapp.com/api/oauth2/authorize?client_id=805958622336778242&scope=bot&permissions=27681","support":"","website":""}
{"owners":{"additional":[],"primary":"676195747904880690"},"ratelimit":{"time":"2021-02-17T21:05:25.489Z"},"state":"verified","tags":["dashboard","economy"],"nsfw":false,"likes":1,"username":"DisBot","botid":"811426586225016852","logo":"https://cdn.discordapp.com/avatars/811426586225016852/23926ad2d00cc5984300f43a971061ea.png?size=256","description":"Want to increase activity on your server DisBot provides tons of in-chat tools.","long":"<p><strong>Want to increase activity on your server.</strong><br />\nDisBot provides tons of in-chat tools.</p>\n\n<p>Whether your server has 5 members or 5000, you can rely on DisBot to make it enjoyable while doing a great job of moderating annoying people. We've included plenty of powerful, customizable commands as well as a robust extension system, making DisBot the only bot you'll need for an awesome Discord experience.</p>\n","prefix":"@mention","note":"Our Main Bot!","servers":null,"github":"","invite":"https://discord.com/oauth2/authorize?client_id=811426586225016852&scope=bot&permissions=470019135","support":"https://discord.gg/Hqp4PfRDqq","website":"https://bot.dishost.ga"}
{"owners":{"additional":[]},"ratelimit":{"time":"2021-02-18T20:40:46.731Z"},"state":"unverified","tags":[],"nsfw":false,"likes":0,"badges":[],"feedback":[{"approved":true,"by":"676195747904880690","message":"this bot is a well done bot and its simplistic to use"}],"totalVotes":0,"votes":[],"listing":{"body":"PartnerBot is your Number Bot for server to server bumping! Advertise your server on a more global scale!\n\nHow does it work?\nPartnerbot works by using each server its currently in and setup with the command `p!init` will be able to see all bumps in that channel from others using this bot! The more servers this bot is in the bigger the list of servers that will see your `p!bump` post!","botId":"805958622336778242","githubURL":"","invite":"https://discord.com/oauth2/authorize?client_id=805958622336778242&scope=bot&permissions=27681","overview":"PartnerBot is your Number Bot for server to server bumping! Advertise your server on a more global scale!","ownerIds":[],"prefix":"p!","supportInvite":"6XJqkA7pQk","websiteURL":"","tags":["utility"]},"ownerId":"676195747904880690","approvedAt":"2021-02-17T20:07:29.297Z","servers":null}
[2021-02-18 20:40:46] [EVENT] /home/runner/discord-bot-list/node_modules/klasa/src/events/unhandledRejection.js
[2021-02-18 20:40:46] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2021-02-18 20:40:46]   "TypeError: Cannot read property 'toLowerCase' of undefined\n" +
[2021-02-18 20:40:46]   '    at /home/runner/discord-bot-list/src/routes/bots/search.js:14:26\n' +
[2021-02-18 20:40:46]   '    at Array.filter (<anonymous>)\n' +
[2021-02-18 20:40:46]   '    at /home/runner/discord-bot-list/src/routes/bots/search.js:12:22\n' +
[2021-02-18 20:40:46]   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)')
[2021-02-18 20:40:46]     at KlasaClient.emit (events.js:304:17)
[2021-02-18 20:40:46]     at module.exports.run (/home/runner/discord-bot-list/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2021-02-18 20:40:46]     at module.exports._run (/home/runner/discord-bot-list/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2021-02-18 20:40:46]     at process.emit (events.js:315:20)
[2021-02-18 20:40:46]     at processPromiseRejections (internal/process/promises.js:209:33)
[2021-02-18 20:40:46]     at processTicksAndRejections (internal/process/task_queues.js:98:32)`

**Comment by ezywebca** [comment]
i had to use repl to pull this up but i build on repl then deploy off to dedicated servers or vps this is already on a vps never issue before so very confused im not sure as to the fix here

**Comment by ezywebca** [comment]
yeah @Sank6 this is the error over and over i get consoled

[2021-02-19 03:00:46] [EVENT] /home/runner/dbl/node_modules/klasa/src/events/unhandledRejection.js
[2021-02-19 03:00:46] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2021-02-19 03:00:46]   "TypeError: Cannot read property 'toLowerCase' of undefined\n" +
[2021-02-19 03:00:46]   '    at /home/runner/dbl/src/routes/bots/search.js:13:26\n' +
[2021-02-19 03:00:46]   '    at Array.filter (<anonymous>)\n' +
[2021-02-19 03:00:46]   '    at /home/runner/dbl/src/routes/bots/search.js:12:22\n' +
[2021-02-19 03:00:46]   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)')
[2021-02-19 03:00:46]     at KlasaClient.emit (events.js:304:17)
[2021-02-19 03:00:46]     at module.exports.run (/home/runner/dbl/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2021-02-19 03:00:46]     at module.exports._run (/home/runner/dbl/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2021-02-19 03:00:46]     at process.emit (events.js:315:20)
[2021-02-19 03:00:46]     at processPromiseRejections (internal/process/promises.js:209:33)
[2021-02-19 03:00:46]     at processTicksAndRejections (internal/process/task_queues.js:98:32)

**Comment by ezywebca** [comment]
and this is fresh out of box ive tested this via repl before and it worked only thing not working is this and im not seeing a search on mobile ether

**Comment by shootdot** [comment]
Can you try clearing your Mongo database and then add bot then try it.

**Comment by ezywebca** [comment]
its not the mongodb @shootdot as this was proveded on a BRAND new deploy to further prove there is error in code

**Comment by shootdot** [comment]
If you can can you provide me the repl link so that I can have a look at it ?

**Comment by shootdot** [comment]
Also Sank6 Sorry I have not been active in this repo because of School works 😔

**Comment by ezywebca** [comment]
was planning on it but seems my repl account atm @shootdot is being slow af give me a few ping u back

**Comment by shootdot** [comment]
It's okay take your time.

**Comment by ezywebca** [comment]
@shootdot https://repl.it/join/pgaeckje-n3wbot

**Comment by ezywebca** [comment]
also change the db name to newblist to newblisttesting if u like that be a blank fresh one never used and watch still wont work

**Comment by shootdot** [comment]
Okay Let me have a look

**Comment by ezywebca** [comment]
![image](https://user-images.githubusercontent.com/70344872/108456623-b4b17680-723e-11eb-99bf-e4591fdb4fc4.png)

**Comment by shootdot** [comment]
@ezywebca Come back to repl

**Comment by ezywebca** [comment]
im on repl @shootdot

**Comment by ezywebca** [comment]
![image](https://user-images.githubusercontent.com/70344872/108456688-da3e8000-723e-11eb-892f-310bae60290d.png)
Whjere u @shootdot

**Comment by shootdot** [comment]
@Sank6 Found the issue. You need to filter unverified bots in the search router. As unverified bots still don't have a username it ends up with error.

**Comment by shootdot** [comment]
Edit the file `src/routes/bots/search.js`
```js
const { Router } = require("express");
const Bots = require("@models/bots");
const getList = require('@utils/getList.js')

const route = Router();

route.get("/", async (req, res) => {
    let search = req.query.q;
    if (!search) search = "";
    search = search.toLowerCase();
    let bots = await Bots.find({})
    let filter = bots.filter(bot => bot.state == "verified")
    let found = filter.filter(fil => {
      if (fil.username.toLowerCase().includes(search)) return true;
      else if (fil.description.toLowerCase().includes(search)) return true;
      else return false;
    })
    if (!found) return res.send({ error: "No bots found for this search" });

    res.render("search", {
        cards: found,
        search,
        user: req.user, req
    });
});

module.exports = route;
```

**Comment by ezywebca** [comment]
Thanks again btw!!

**Comment by Sank6** [comment]
Thank you @shootdot . I'll add this later today.

**Comment by Sank6** [comment]
Fixed in dev branch
