### ISSUE TITLE
Site error

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#497]
Error: Failed to lookup view "index" in views directory "src/dynamic"
    at Function.render (/root/Discord-Bot-List/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/root/Discord-Bot-List/node_modules/express/lib/response.js:1012:7)
    at /root/Discord-Bot-List/src/routes/index.js:19:27
    at Layer.handle [as handle_request] (/root/Discord-Bot-List/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/Discord-Bot-List/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/Discord-Bot-List/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/Discord-Bot-List/node_modules/express/lib/router/layer.js:95:5)
    at /root/Discord-Bot-List/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:335:12)
    at next (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:174:3)
    at router (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/Discord-Bot-List/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:317:13)
    at /root/Discord-Bot-List/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:335:12)

**Comment by Zaid-maker** [comment]
Because you give wrong npm command.

Sent from Mail for Windows 10

From: Vortex_
Sent: Sunday, February 28, 2021 9:49 PM
To: Sank6/Discord-Bot-List
Cc: Subscribed
Subject: [Sank6/Discord-Bot-List] Site error (#497)

Error: Failed to lookup view "index" in views directory "src/dynamic"
at Function.render (/root/Discord-Bot-List/node_modules/express/lib/application.js:580:17)
at ServerResponse.render (/root/Discord-Bot-List/node_modules/express/lib/response.js:1012:7)
at /root/Discord-Bot-List/src/routes/index.js:19:27
at Layer.handle [as handle_request] (/root/Discord-Bot-List/node_modules/express/lib/router/layer.js:95:5)
at next (/root/Discord-Bot-List/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/root/Discord-Bot-List/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/root/Discord-Bot-List/node_modules/express/lib/router/layer.js:95:5)
at /root/Discord-Bot-List/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:335:12)
at next (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:275:10)
at Function.handle (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:174:3)
at router (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:47:12)
at Layer.handle [as handle_request] (/root/Discord-Bot-List/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:317:13)
at /root/Discord-Bot-List/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/root/Discord-Bot-List/node_modules/express/lib/router/index.js:335:12)
