### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lunadraws** [Sank6/Discord-Bot-List#514]
Hi i have a problem its me this error message 

Error: ENOENT: no such file or directory, open '../../../../../etc/letsencrypt/live/faster-bots.com/privkey.pem'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\Users\Nava\Documents\discord-bot-list\src\structures\app.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Nava\Documents\discord-bot-list\src\index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '../../../../../etc/letsencrypt/live/faster-bots.com/privkey.pem'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-bot-list@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-bot-list@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nava\AppData\Roaming\npm-cache\_logs\2021-04-03T09_26_39_483Z-debug.log

**Comment by Zaid-maker** [comment]
You messed up with something

**Comment by nickdevnl** [comment]
You dod something wrong with your ssl cert

**Comment by Sank6** [comment]
Yeah it looks like something to do with letsencrypt
