### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nim1com** [Sank6/Discord-Bot-List#520]
> discordbotlist@3.0.0 start
> node src/index.js

C:\Users\nikla\Desktop\GITHUB\Discord-Bot-List\node_modules\discord.js\src\util\BitField.js:151
    throw new RangeError('BITFIELD_INVALID', bit);
    ^

RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: 3072.
    at Function.resolve (C:\Users\nikla\Desktop\GITHUB\Discord-Bot-List\node_modules\discord.js\src\util\BitField.js:151:11)
    at new BitField (C:\Users\nikla\Desktop\GITHUB\Discord-Bot-List\node_modules\discord.js\src\util\BitField.js:17:38)
    at new Permissions (C:\Users\nikla\Desktop\GITHUB\Discord-Bot-List\node_modules\discord.js\src\util\Permissions.js:11:1)
    at Object.<anonymous> (C:\Users\nikla\Desktop\GITHUB\Discord-Bot-List\node_modules\klasa\src\lib\Client.js:505:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\nikla\Desktop\GITHUB\Discord-Bot-List\node_modules\klasa\src\index.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  [Symbol(code)]: 'BITFIELD_INVALID'
}

**Comment by Nim1com** [comment]
Stuff is filled correctly
 but the roles are not yet done
