### ISSUE TITLE
Embed bug

### ISSUE THREAD

**Issue by crt-romain78** [Sank6/Discord-Bot-List#544]
![image](https://user-images.githubusercontent.com/75182534/118850703-58a7ce00-b8d1-11eb-85d2-6ff269c0b59e.png)

there is a ss of the embed shown when I click on embed

**Comment by Zaid-maker** [comment]
Any error in console?

**Comment by crt-romain78** [comment]
yes there is a error:

[2021-05-23 11:59:28] [EVENT] /root/bot-list/node_modules/klasa/src/events/unhandledRejection.js
[2021-05-23 11:59:28] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
[2021-05-23 11:59:28]   "Error: ENOENT, No such file or directory '/root/bot-list/src/routes/api/verified_badge.png'\n" +
[2021-05-23 11:59:28]   '    at setSource (/root/bot-list/node_modules/canvas/lib/image.js:91:13)\n' +
[2021-05-23 11:59:28]   '    at Image.set (/root/bot-list/node_modules/canvas/lib/image.js:62:9)\n' +
[2021-05-23 11:59:28]   '    at /root/bot-list/node_modules/canvas/index.js:34:15\n' +
[2021-05-23 11:59:28]   '    at new Promise (<anonymous>)\n' +
[2021-05-23 11:59:28]   '    at Object.loadImage (/root/bot-list/node_modules/canvas/index.js:23:10)\n' +
[2021-05-23 11:59:28]   '    at exports.resolveImage (/root/bot-list/node_modules/canvas-constructor/dist/index.js:1:11728)\n' +
[2021-05-23 11:59:28]   '    at /root/bot-list/src/routes/api/embed.js:17:26\n' +
[2021-05-23 11:59:28]   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)')
[2021-05-23 11:59:28]     at KlasaClient.emit (events.js:303:17)
[2021-05-23 11:59:28]     at module.exports.run (/root/bot-list/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2021-05-23 11:59:28]     at module.exports._run (/root/bot-list/node_modules/klasa/src/lib/structures/Event.js:101:15)
[2021-05-23 11:59:28]     at process.emit (events.js:314:20)
[2021-05-23 11:59:28]     at processPromiseRejections (internal/process/promises.js:209:33)
[2021-05-23 11:59:28]     at processTicksAndRejections (internal/process/task_queues.js:98:32)


and when I try to do the embed directly from the bot it does the same thing

**Comment by Sank6** [comment]
Make sure you have the file `verified_badge.png` in the `src/routes/api` folder.
