### ISSUE TITLE
Problem when log in (Replit project)

### ISSUE THREAD

**Issue by NoSoyDany** [Sank6/Discord-Bot-List#551]
Hello! When i log in with my discord account it give to me this error in webpage:

TokenError: Invalid "redirect_uri" in request.
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/ddes/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/ddes/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/runner/ddes/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/runner/ddes/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/ddes/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/ddes/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by NoSoyDany** [comment]
https://prnt.sc/13ra4cl

**Comment by DJHARDY2K21** [comment]
I get the same, I'm also trying to setup the OAuth

**Comment by Zaid-maker** [comment]
obviously you have to setup the redirect in your discord bot application,.

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri
