### ISSUE TITLE
module not found, can't install

### ISSUE THREAD

**Issue by pherngpy** [Sank6/Discord-Bot-List#553]
console log : 
```js
 npm start

> discordbotlist@3.0.0 start /home/runner/Discord-Bot-List
> node src/index.js

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'module-alias/register'
Require stack:
- /home/runner/Discord-Bot-List/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/Discord-Bot-List/src/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Discord-Bot-List/src/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discordbotlist@3.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discordbotlist@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-15T03_12_23_884Z-debug.log
exit status 1
 
```
when i do
npm install module-alias/register
console log:
```js
 npm i module-alias/register
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/module-alias/register.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-15T03_14_11_133Z-debug.log
 
```
please help me
platform : linux
hosting on : replit

**Comment by pherngpy** [comment]
it fixed
