### ISSUE TITLE
Error: Cannot find module 'module-alias/register'

### ISSUE THREAD

**Issue by DBMfan** [Sank6/Discord-Bot-List#556]
Hello,
I'm getting a new error on the bot list:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'module-alias/register'
Require stack:
- /app/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/app/src/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/src/index.js' ]
}
```

**Comment by DevJaxob** [comment]
Check your node version

**Comment by DBMfan** [comment]
The node version is 14

**Comment by eitanmdk** [comment]
this happend to me too please help meeee

**Comment by LuckyTarget** [comment]
npm uninstall and install again.
`npm uninstall i`
`npm install`
`npm i canvas`
`npm i register`

**Comment by Ade-Hermansyah** [comment]
what your webiste give me bot list web

**Comment by LuckyTarget** [comment]
> what your webiste give me bot list web

check my profile

**Comment by Sank6** [comment]
Try `npm i module-alias`
