### ISSUE TITLE
error when add bots

### ISSUE THREAD

**Issue by Shadowv7** [Sank6/Discord-Bot-List#57]
```[2020-04-26 12:16:14] [EVENT] /rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/events/unhandledRejection.js
[2020-04-26 12:16:14] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \nMongoError: E11000 duplicate key error ' +
[2020-04-26 12:16:14]   'collection: test.bots index: botid_1 dup key: { botid: ' +
[2020-04-26 12:16:14]   '"694247204981833839" }\n    at Function.create ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/core/error.js:43:12)\n' +
[2020-04-26 12:16:14]   '    at toError ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/utils.js:149:22)\n' +
[2020-04-26 12:16:14]   '    at ' +
[2020-04-26 12:16:14]   '/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/operations/common_functions.js:265:39\n' +
[2020-04-26 12:16:14]   '    at handler ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/core/sdam/topology.js:913:24)\n' +
[2020-04-26 12:16:14]   '    at ' +
[2020-04-26 12:16:14]   '/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/connection_pool.js:352:13\n' +
[2020-04-26 12:16:14]   '    at handleOperationResult ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/core/sdam/server.js:489:5)\n' +
[2020-04-26 12:16:14]   '    at MessageStream.messageHandler ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/connection.js:270:5)\n' +
[2020-04-26 12:16:14]   '    at MessageStream.emit (events.js:196:13)\n    at processIncomingData ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n' +
[2020-04-26 12:16:14]   '    at MessageStream._write ' +
[2020-04-26 12:16:14]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n' +
[2020-04-26 12:16:14]   '    at doWrite (_stream_writable.js:417:12)\n    at writeOrBuffer ' +
[2020-04-26 12:16:14]   '(_stream_writable.js:401:5)\n    at MessageStream.Writable.write ' +
[2020-04-26 12:16:14]   '(_stream_writable.js:301:11)\n    at TLSSocket.ondata ' +
[2020-04-26 12:16:14]   '(_stream_readable.js:696:22)\n    at TLSSocket.emit (events.js:196:13)\n    ' +
[2020-04-26 12:16:14]   'at addChunk (_stream_readable.js:290:12)')
[2020-04-26 12:16:14]     at KlasaClient.emit (events.js:185:17)
[2020-04-26 12:16:14]     at module.exports.run (/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-04-26 12:16:14]     at module.exports._run (/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-04-26 12:16:14]     at process.emit (events.js:196:13)
[2020-04-26 12:16:14]     at processPromiseRejections (internal/process/promises.js:165:18)
[2020-04-26 12:16:14]     at processTicksAndRejections (internal/process/task_queues.js:89:32)
[2020-04-26 12:16:33] [EVENT] /rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/events/unhandledRejection.js
[2020-04-26 12:16:33] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \nMongoError: E11000 duplicate key error ' +
[2020-04-26 12:16:33]   'collection: test.bots index: botid_1 dup key: { botid: ' +
[2020-04-26 12:16:33]   '"694247204981833839" }\n    at Function.create ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/core/error.js:43:12)\n' +
[2020-04-26 12:16:33]   '    at toError ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/utils.js:149:22)\n' +
[2020-04-26 12:16:33]   '    at ' +
[2020-04-26 12:16:33]   '/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/operations/common_functions.js:265:39\n' +
[2020-04-26 12:16:33]   '    at handler ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/core/sdam/topology.js:913:24)\n' +
[2020-04-26 12:16:33]   '    at ' +
[2020-04-26 12:16:33]   '/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/connection_pool.js:352:13\n' +
[2020-04-26 12:16:33]   '    at handleOperationResult ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/core/sdam/server.js:489:5)\n' +
[2020-04-26 12:16:33]   '    at MessageStream.messageHandler ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/connection.js:270:5)\n' +
[2020-04-26 12:16:33]   '    at MessageStream.emit (events.js:196:13)\n    at processIncomingData ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n' +
[2020-04-26 12:16:33]   '    at MessageStream._write ' +
[2020-04-26 12:16:33]   '(/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.registry.npmjs.org/mongodb/3.5.6/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n' +
[2020-04-26 12:16:33]   '    at doWrite (_stream_writable.js:417:12)\n    at writeOrBuffer ' +
[2020-04-26 12:16:33]   '(_stream_writable.js:401:5)\n    at MessageStream.Writable.write ' +
[2020-04-26 12:16:33]   '(_stream_writable.js:301:11)\n    at TLSSocket.ondata ' +
[2020-04-26 12:16:33]   '(_stream_readable.js:696:22)\n    at TLSSocket.emit (events.js:196:13)\n    ' +
[2020-04-26 12:16:33]   'at addChunk (_stream_readable.js:290:12)')
[2020-04-26 12:16:33]     at KlasaClient.emit (events.js:185:17)
[2020-04-26 12:16:33]     at module.exports.run (/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-04-26 12:16:33]     at module.exports._run (/rbd/pnpm-volume/bfd7ec82-e0c9-4500-8d77-e35755dfe7b4/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-04-26 12:16:33]     at process.emit (events.js:196:13)
[2020-04-26 12:16:33]     at processPromiseRejections (internal/process/promises.js:165:18)
[2020-04-26 12:16:33]     at processTicksAndRejections (internal/process/task_queues.js:89:32)```

**Comment by bobby365** [comment]
i get that too

**Comment by Misly16** [comment]
yup, started getting that error too.

**Comment by GamearooCodes** [comment]
i get it as well

**Comment by Vulsa** [comment]
When I delete a column (a bot) on mongodb and add the bot again (for my tests), it redirects me to "/error/?e=unknown" and when I go to my profile, it tells me that the bot is checked and exists and has recreated the column in mongodb.

**Comment by Sank6** [comment]
Works for me. Are you not using the resubmit function of the  bot?

**Comment by Konrad570** [comment]
What if u close your cluster and create a new one?
