### ISSUE TITLE
memberCheck Error

### ISSUE THREAD

**Issue by KyleBurnip** [Sank6/Discord-Bot-List#64]
When submitting a bot the code provided in the source:
`
    let [user, tk] = await getUser(req.cookies["refresh_token"]);
    res.cookie("refresh_token", tk, {httpOnly: true});
    let memberCheck = req.app.get('client').guilds.get(GUILD_ID).member(user.id);
`

is giving this error upon trying to add a bot when clicking sumbit

`[2020-05-06 09:57:20] [EVENT] /rbd/pnpm-volume/002f7f68-9b40-4a3d-8777-2669be5e1f57/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/events/unhandledRejection.js
[2020-05-06 09:57:20] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \nTypeError: req.app.get(...).guilds.get is ' +
[2020-05-06 09:57:20]   'not a function\n    at /app/src/routes/api/bots/submit.js:28:52\n    ' +
[2020-05-06 09:57:20]   'at processTicksAndRejections (internal/process/task_queues.js:88:5)')
[2020-05-06 09:57:20]     at KlasaClient.emit (events.js:185:17)
[2020-05-06 09:57:20]     at module.exports.run (/rbd/pnpm-volume/002f7f68-9b40-4a3d-8777-2669be5e1f57/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-05-06 09:57:20]     at module.exports._run (/rbd/pnpm-volume/002f7f68-9b40-4a3d-8777-2669be5e1f57/node_modules/.github.com/dirigeants/klasa/7fbd351c1276a171fdc854bc99f05b5ef89eb32b/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-05-06 09:57:20]     at process.emit (events.js:196:13)
[2020-05-06 09:57:20]     at processPromiseRejections (internal/process/promises.js:165:18)
[2020-05-06 09:57:20]     at processTicksAndRejections (internal/process/task_queues.js:89:32)`

**Comment by Gouthamkc** [comment]
same

**Comment by Vulsa** [comment]
You must add the bot you prepared on your discord server

**Comment by Misly16** [comment]
You also must fill out all of the contents in `.env`

**Comment by Sank6** [comment]
I changed the way that section of code works. I don't know why you got that error, but if it still happens, can you send the new error.
