### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HaryoPratama** [Sank6/Discord-Bot-List#67]
Help! 

![image](https://user-images.githubusercontent.com/62017665/81916730-ba00d700-95c3-11ea-8d03-09b187c3cb39.png)

**Comment by Misly16** [comment]
Are you using the correct mongodb atlas url

**Comment by HaryoPratama** [comment]
> Are you using the correct mongodb atlas url. Also have you white listed all ips

I don't know what the correct mongodb atlas url can you help me?

**Comment by HaryoPratama** [comment]
Can you help it on it?

**Comment by Misly16** [comment]
Have you made a mongodb account?

**Comment by HaryoPratama** [comment]
> Have you made a mongodb account?

Already create mongodb account

**Comment by HaryoPratama** [comment]
But where I can know mongodb url?

**Comment by HaryoPratama** [comment]
Help me?

**Comment by shivamthakkar** [comment]
> Help me?

Find out at youtube

**Comment by Misly16** [comment]
Create a user here.
![image](https://user-images.githubusercontent.com/60405462/82128459-5b9a4b00-97b3-11ea-94f5-8abea5e7972e.png)

Go back to clusters and press the connect button 
![image](https://user-images.githubusercontent.com/60405462/82128491-8389ae80-97b3-11ea-85bb-eca78109a632.png)
Then press connect your application making sure you whitelist the user you made and the ip 0.0.0.0
After that you will get the url that you will have to replace the password with the users password
@HaryoPratama

**Comment by HaryoPratama** [comment]
Thanks,i will try it

**Comment by HaryoPratama** [comment]
after that what i can do?

**Comment by Misly16** [comment]
Put that link in the .env file where it asks for it

**Comment by HaryoPratama** [comment]
done
but its like require password from database access right?

**Comment by HaryoPratama** [comment]
also can i run it on glitch.com?

**Comment by Misly16** [comment]
Yes replace <password> with the database users password

**Comment by Misly16** [comment]
And yes it can be ran on glitch

**Comment by HaryoPratama** [comment]
i done but what the domain like needed? 
![image](https://user-images.githubusercontent.com/62017665/82131904-b63ea180-97c9-11ea-9d32-9b15e354d2ab.png)

**Comment by HaryoPratama** [comment]
i only add https://

**Comment by Misly16** [comment]
Its the domain you're hosting it on but I would recommend for you to learn some html/js before hosting this

**Comment by HaryoPratama** [comment]
nah i got error

.env: line 33: Buggy: No such file or directory
(node:4102) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/.
    at new MongooseServerSelectionError (/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/mongoose/5.9.14/node_modules/mongoose/lib/error/serverSelection.js:24:11)
    at NativeConnection.Connection.openUri (/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/mongoose/5.9.14/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/mongoose/5.9.14/node_modules/mongoose/lib/index.js:333:15)
at /app/src/index.js:12:20
at Object.<anonymous> (/app/src/index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
(node:4102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

its say my mongodb is No such file or directory

**Comment by HaryoPratama** [comment]
all my ip is whitelisted

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82131949-1c2b2900-97ca-11ea-9a6d-161f361f8dc6.png)

**Comment by Misly16** [comment]
What ip have you white listed?

**Comment by HaryoPratama** [comment]
My ip and you say be4

**Comment by Misly16** [comment]
Did you white list the ip 0.0.0.0

**Comment by HaryoPratama** [comment]
yeah
are its wrong?

**Comment by Misly16** [comment]
Did you replace <password> with the users password?

**Comment by HaryoPratama** [comment]
only 1 right?

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82131980-7926df00-97ca-11ea-8363-d6eb2c14be51.png)

**Comment by Misly16** [comment]
Yes did you replace the url strings password with that users password

**Comment by HaryoPratama** [comment]
yups at <password> like and changed to <My Password>

**Comment by HaryoPratama** [comment]
<>

**Comment by HaryoPratama** [comment]
<password>

**Comment by HaryoPratama** [comment]
wait i can say that

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132011-cdca5a00-97ca-11ea-9159-27c6224ad44c.png)

**Comment by Misly16** [comment]
Then you must have made a mistake somewhere as its not connecting, I would suggest deleting and making a newbuser making sure that you give 0.0.0.0 access to it

**Comment by Misly16** [comment]
No you have to remove <>

**Comment by HaryoPratama** [comment]
Ook i see so its look like MyPassword right?
![image](https://user-images.githubusercontent.com/62017665/82132030-f7838100-97ca-11ea-862a-e637dec74b23.png)

**Comment by Misly16** [comment]
Also what string have you provided in the env but make sure you remove the password when posting it here

**Comment by HaryoPratama** [comment]
okay btw that not my password
also
![image](https://user-images.githubusercontent.com/62017665/82132060-15e97c80-97cb-11ea-9779-6efcdfd5b394.png)
what i choose?

**Comment by HaryoPratama** [comment]
mongodb+srv://Buggy:<MY PASSWORD>@cluster0-ifvr6.mongodb.net/test?retryWrites=true&w=majority

**Comment by HaryoPratama** [comment]
this one

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132068-387b9580-97cb-11ea-9b39-75718cb9a699.png)

**Comment by Misly16** [comment]
Seems right, now you need to make sure you white listed **all** ips

**Comment by HaryoPratama** [comment]
i whitelisted my ip

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132085-8395a880-97cb-11ea-8187-f49e905757be.png)

**Comment by Misly16** [comment]
You need to whitelist all ips not just yours as you're not hosting it locally

**Comment by HaryoPratama** [comment]
what the ip i need whitelist?

**Comment by Misly16** [comment]
As I said many times above you need to whitelist 0.0.0.0

**Comment by HaryoPratama** [comment]
i already..

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132112-d66f6000-97cb-11ea-890c-7d629c854b15.png)

**Comment by Misly16** [comment]
Try running refresh in the glitch console and try again

**Comment by HaryoPratama** [comment]
okay

**Comment by HaryoPratama** [comment]
.env: line 33: Buggy: No such file or directory

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132152-3108bc00-97cc-11ea-99d3-49a556b8fb7c.png)

**Comment by Misly16** [comment]
Don't put the <> in and I would suggest using a randomly generated password

**Comment by HaryoPratama** [comment]
ok

**Comment by HaryoPratama** [comment]
its working now

**Comment by HaryoPratama** [comment]
wait also

**Comment by Misly16** [comment]
> wait also

Yes?

**Comment by HaryoPratama** [comment]
to make the login for authorize i need make like 

Also on the developer application, add your redirect URI under the oauth2 tab. Set it to your domain and then /api/callback. For example, https://botlist.com/api/callback
Install the required dependencies: npm i.

right

**Comment by HaryoPratama** [comment]
add /api/callback

**Comment by HaryoPratama** [comment]
because i get 
![image](https://user-images.githubusercontent.com/62017665/82132197-b7250280-97cc-11ea-8080-302450add03d.png)

**Comment by Misly16** [comment]
What url have you provided to discord

**Comment by HaryoPratama** [comment]
its not done, at the bot developer portal i need add redirect ? for login

**Comment by Misly16** [comment]
Also make sure you have fully filled all the fields in .env out

**Comment by Misly16** [comment]
Yes you need to add it in the dev portal as per instructions

**Comment by HaryoPratama** [comment]
yeah already

**Comment by HaryoPratama** [comment]
let me try

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132234-14b94f00-97cd-11ea-8f59-1dfde463da83.png)
like this right? on OAuth2

**Comment by Misly16** [comment]
Yes you do

**Comment by HaryoPratama** [comment]
also what the 
![image](https://user-images.githubusercontent.com/62017665/82132244-37e3fe80-97cd-11ea-97d8-bcb2d54e601c.png) scopes i need?

**Comment by Misly16** [comment]
The app should ask for them automatically without you giving it a discord link

**Comment by HaryoPratama** [comment]
so i not need any scopes?

**Comment by Misly16** [comment]
No because youre not putting a discord link anywhere.....

**Comment by HaryoPratama** [comment]
okay but wait

**Comment by HaryoPratama** [comment]
wait what i cant login

**Comment by Misly16** [comment]
What errors are you getting?

**Comment by HaryoPratama** [comment]
its keep on {"redirect_uri": ["Not a well formed URL."]} but on web

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132305-e1c38b00-97cd-11ea-9564-8cde1249d30e.png)
on logs didnt error

**Comment by Misly16** [comment]
Can you send the url in here?

**Comment by HaryoPratama** [comment]
https://discordbots-ind.glitch.me/ i try using glitch

**Comment by Misly16** [comment]
I'm talking about the oath url where it errors

**Comment by Misly16** [comment]
You havent even put the domain in discords redirect

**Comment by Misly16** [comment]
That and/or you havent put the domain in .env

**Comment by HaryoPratama** [comment]
errors on {"redirect_uri": ["Not a well formed URL."]} when i want login

**Comment by HaryoPratama** [comment]
ok wait

**Comment by HaryoPratama** [comment]
at .env need the web too or just
{"redirect_uri": ["Not a well formed URL."]}

**Comment by Misly16** [comment]
You need to enter the domain on both the discord panel and the .env

**Comment by HaryoPratama** [comment]
Ok i see but i already give the domain both and the url its 
![image](https://user-images.githubusercontent.com/62017665/82132455-6b278d00-97cf-11ea-9920-329121fa7e1c.png)

**Comment by Misly16** [comment]
You need to put the domain in the discord panel too

**Comment by HaryoPratama** [comment]
on  OAuth2 Redirects?

**Comment by Misly16** [comment]
Yes like this https://discordbots-ind.glitch.me/api/callback

**Comment by HaryoPratama** [comment]
okay thanks let me try

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132491-d1141480-97cf-11ea-8a55-8309e2a80c99.png)

**Comment by Misly16** [comment]
Thats all

**Comment by Misly16** [comment]
now try to login

**Comment by HaryoPratama** [comment]
okay

**Comment by HaryoPratama** [comment]
keep

**Comment by HaryoPratama** [comment]
on the login.js ttps://discordapp.com/api/oauth2/authorize?client_id=${CLIENT_ID}&response_type=code&scope=identify&redirect_uri=${encodeURIComponent(DOMAIN)}/api/callback

**Comment by Misly16** [comment]
> keep

?

**Comment by HaryoPratama** [comment]
and redirect to https://discord.com/oauth2/authorize?client_id=710406728277295174&response_type=code&scope=identify&redirect_uri=https%3A%2F%2Fdiscordbots-ind.glitch.me%2F/api/callback , try it

**Comment by HaryoPratama** [comment]
invalid OAuth2 redirect url

**Comment by Misly16** [comment]
That should work

**Comment by HaryoPratama** [comment]
at this link https://discord.com/oauth2/authorize?client_id=710406728277295174&response_type=code&scope=identify&redirect_uri=https%3A%2F%2Fdiscordbots-ind.glitch.me%2F/api/callback not working when redirect to login

**Comment by Misly16** [comment]
What happens when you login

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/82132545-5a2b4b80-97d0-11ea-8bdc-7679842b909c.png)

**Comment by Misly16** [comment]
Ok, idk ill answer this tommorow when I get a chance to think

**Comment by HaryoPratama** [comment]
okay

**Comment by HaryoPratama** [comment]
[2020-05-16 23:55:06] [EVENT] /rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.github.com/dirigeants/klasa/48e9eed5227a02119cd6082bf66d076006f86fce/node_modules/klasa/src/events/unhandledRejection.js
[2020-05-16 23:55:06] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \nError: NoCodeProvided\n    at ' +
[2020-05-16 23:55:06]   '/app/src/routes/api/callback.js:10:32\n    at Layer.handle [as ' +
[2020-05-16 23:55:06]   'handle_request] ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
[2020-05-16 23:55:06]   '    at next ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)\n' +
[2020-05-16 23:55:06]   '    at Route.dispatch ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)\n' +
[2020-05-16 23:55:06]   '    at Layer.handle [as handle_request] ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
[2020-05-16 23:55:06]   '    at ' +
[2020-05-16 23:55:06]   '/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22\n' +
[2020-05-16 23:55:06]   '    at Function.process_params ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)\n' +
[2020-05-16 23:55:06]   '    at next ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)\n' +
[2020-05-16 23:55:06]   '    at Function.handle ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:174:3)\n' +
[2020-05-16 23:55:06]   '    at router ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:47:12)\n' +
[2020-05-16 23:55:06]   '    at Layer.handle [as handle_request] ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
[2020-05-16 23:55:06]   '    at trim_prefix ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:317:13)\n' +
[2020-05-16 23:55:06]   '    at ' +
[2020-05-16 23:55:06]   '/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:284:7\n' +
[2020-05-16 23:55:06]   '    at Function.process_params ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)\n' +
[2020-05-16 23:55:06]   '    at next ' +
[2020-05-16 23:55:06]   '(/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)\n' +
[2020-05-16 23:55:06]   '    at /app/src/routes/api/index.js:20:5')
[2020-05-16 23:55:06]     at KlasaClient.emit (events.js:185:17)
[2020-05-16 23:55:06]     at module.exports.run (/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.github.com/dirigeants/klasa/48e9eed5227a02119cd6082bf66d076006f86fce/node_modules/klasa/src/events/unhandledRejection.js:12:15)
[2020-05-16 23:55:06]     at module.exports._run (/rbd/pnpm-volume/8f9d3766-fc17-4b2c-902b-ce123016cb9a/node_modules/.github.com/dirigeants/klasa/48e9eed5227a02119cd6082bf66d076006f86fce/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-05-16 23:55:06]     at process.emit (events.js:196:13)
[2020-05-16 23:55:06]     at processPromiseRejections (internal/process/promises.js:165:18)
[2020-05-16 23:55:06]     at processTicksAndRejections (internal/process/task_queues.js:89:32)

**Comment by HaryoPratama** [comment]
solved all

**Comment by ForSomeReasonsYT** [comment]
@HaryoPratama How did you solve the 
![image](https://user-images.githubusercontent.com/66392625/88240828-fd955280-cc90-11ea-920c-4522eacd5c54.png)
i still have it

**Comment by ForSomeReasonsYT** [comment]
@Sank6 Help me fix this please

**Comment by Misly16** [comment]
Don't post the same thing on multiple issues

**Comment by sayantan300** [comment]
@ForSomeReasonsYT change ur domain on env file from `https://rovelbotlist.glitch.me/` to `https://rovelbotlist.glitch.me` (remove slash at last) and see if it works

**Comment by HideakiAtsuyo** [comment]
Invalid OAuth2 redirect url: https://i.imgur.com/qkbfaAm.png & https://i.imgur.com/wn4wOFl.png (you can choose the port) & https://i.imgur.com/7D9kFIT.png
=====================
The mongo url: https://i.imgur.com/DFa92OO.png (Config a user) & Create a db collection https://i.imgur.com/zdH3tIz.png (you can choose the name no one care) & the url = 
https://i.imgur.com/idPYgyw.png
https://i.imgur.com/ue5Zz9i.png
https://i.imgur.com/WLPxC2W.png

Final url example: `mongodb+srv://TheUsername:ThePassword@cluster0.vsol6.gcp.mongodb.net/thedbname`

**Comment by Misly16** [comment]
You can disable the code grant as you dont need it

**Comment by HideakiAtsuyo** [comment]
> 
> 
> You can disable the code grant as you dont need it

no, you need it to login ;)

**Comment by Misly16** [comment]
> > 
> > 
> > You can disable the code grant as you dont need it
> 
> no, you need it to login ;)

No, no you don't
