### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JLDENSMORE** [Sank6/Discord-Bot-List#74]
Umm what does this mean:
```
node v12.0.0, npm 6.9.0

Installing...

npm WARN discord.js@12.2.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.

npm WARN discord.js@12.2.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.

npm WARN discord.js@12.2.0 requires a peer of libsodium-wrappers@^0.7.6 but none is installed. You must install peer dependencies yourself.

npm WARN discord.js@12.2.0 requires a peer of sodium@^3.0.2 but none is installed. You must install peer dependencies yourself.

npm WARN discord.js@12.2.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm WARN discord.js@12.2.0 requires a peer of zlib-sync@^0.1.6 but none is installed. You must install peer dependencies yourself.

npm WARN klasa@0.6.0-dev requires a peer of @klasa/core@^0.0.3 but none is installed. You must install peer dependencies yourself.

npm WARN klasa@0.6.0-dev requires a peer of @klasa/dapi-types@^0.2.0 but none is installed. You must install peer dependencies yourself.

npm WARN prism-media@1.2.2 requires a peer of ffmpeg-static@^2.4.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN prism-media@1.2.2 requires a peer of @discordjs/opus@^0.1.0 but none is installed. You must install peer dependencies yourself.

npm WARN prism-media@1.2.2 requires a peer of node-opus@^0.3.1 but none is installed. You must install peer dependencies yourself.

npm WARN prism-media@1.2.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.

npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.

npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm WARN discordbotlist@3.0.0 No repository field.

npm WARN discordbotlist@3.0.0 No license field.

audited 264 packages in 2.575s
found 0 vulnerabilities
Total install time: 5734ms```

**Comment by Misly16** [comment]
These are just warnings, totally normal

**Comment by JLDENSMORE** [comment]
Oops I meant to send this:

```
internal/modules/cjs/loader.js:235

      throw err;

      ^

Error: Cannot find module '/app/node_modules/klasa/dist/src/index.js'. Please verify that the package.json has a valid "main" entry

    at tryPackage (internal/modules/cjs/loader.js:227:19)

    at Function.Module._findPath (internal/modules/cjs/loader.js:364:18)

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:597:27)

    at Function.Module._resolveFilename (/app/node_modules/module-alias/index.js:49:29)

    at Function.Module._load (internal/modules/cjs/loader.js:526:27)

    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)

at Object.<anonymous> (/app/src/bot/index.js:2:28)

    at Module._compile (internal/modules/cjs/loader.js:759:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)

    at Function.Module._load (internal/modules/cjs/loader.js:555:12)

    at Module.require (internal/modules/cjs/loader.js:666:19)

    at require (internal/modules/cjs/helpers.js:16:16)

Jump Toat Object.<anonymous> (/app/src/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:759:30)

**Comment by Misly16** [comment]
Google npm debug, as I don't remember the commands

**Comment by JLDENSMORE** [comment]
Hmm, I can't find anything about this issue.

**Comment by crazyartz666** [comment]
Any1 can help with this

**Comment by Zaid-maker** [comment]
Because you don't specify your main file in package.json file

**Comment by crazyartz666** [comment]
Do you fix it @JLDENSMORE

**Comment by JLDENSMORE** [comment]
> Do you fix it @JLDENSMORE

@crazyartz666 No I did not I closed it because there are already many open about the same issue.
