### ISSUE TITLE
What does this mean

### ISSUE THREAD

**Issue by EvanHanna12** [Sank6/Discord-Bot-List#75]
Uncaught Promise Error: 
TypeError: Cannot read property 'prototype' of undefined
    at module.exports.enable (/app/node_modules/klasa/src/lib/structures/Extendable.js:126:88)
    at module.exports.init (/app/node_modules/klasa/src/lib/structures/Extendable.js:102:26)
    at /app/node_modules/klasa/src/lib/structures/interfaces/Store.js:23:62
    at /app/node_modules/@discordjs/collection/dist/index.js:219:20
    at Function.from (<anonymous>)
    at Map.map (/app/node_modules/@discordjs/collection/dist/index.js:217:22)
    at Map.init (/app/node_modules/klasa/src/lib/structures/interfaces/Store.js:23:27)
    at /app/node_modules/klasa/src/lib/Client.js:394:101
    at /app/node_modules/@discordjs/collection/dist/index.js:219:20
    at Function.from (<anonymous>)
    at Map.map (/app/node_modules/@discordjs/collection/dist/index.js:217:22)
    at KlasaClient._ready (/app/node_modules/klasa/src/lib/Client.js:394:82)

**Comment by Sank6** [comment]
Make sure you're using the correct version of Klasa
