### ISSUE TITLE
internal/modules/cjs/loader.js:235       throw err;

### ISSUE THREAD

**Issue by tireder** [Sank6/Discord-Bot-List#80]
internal/modules/cjs/loader.js:235
      throw err;
      ^
Error: Cannot find module '/app/node_modules/klasa/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:227:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:364:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:597:27)
    at Function.Module._resolveFilename (/rbd/pnpm-volume/e8679101-8d2f-4985-9608-ffd6544bd0a0/node_modules/.registry.npmjs.org/module-alias/2.2.2/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/src/bot/index.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/src/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:759:30)

**Comment by Zaid-maker** [comment]
Yes getting same errors over and over again.

**Comment by tireder** [comment]
So any help?

**Comment by Zaid-maker** [comment]
Idk I think there's problem with nodejs

**Comment by tireder** [comment]
reinstalled klasa 

- [ ] (solved)

**Comment by Zaid-maker** [comment]
Are u sure

**Comment by tireder** [comment]
Ye
