### ISSUE TITLE
MongooseServerSelectionError: bad auth Authentication failed.

### ISSUE THREAD

**Issue by HaryoPratama** [Sank6/Discord-Bot-List#84]
i need help with this

(node:674) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: bad auth Authentication failed.
    at NativeConnection.Connection.openUri (/rbd/pnpm-volume/c004d856-4f55-45f2-887a-3a08d530d21f/node_modules/.registry.npmjs.org/mongoose/5.9.19/node_modules/mongoose/lib/connection.js:826:32)
    at Mongoose.connect (/rbd/pnpm-volume/c004d856-4f55-45f2-887a-3a08d530d21f/node_modules/.registry.npmjs.org/mongoose/5.9.19/node_modules/mongoose/lib/index.js:335:15)
at /app/src/index.js:12:20
at Object.<anonymous> (/app/src/index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
(node:674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Misly16** [comment]
Did you provide a correct mongo url?

**Comment by HaryoPratama** [comment]
yeah but mongodb like have a new update maybe its like <dbname> but i using old url

**Comment by HaryoPratama** [comment]
![image](https://user-images.githubusercontent.com/62017665/85285068-c2301a00-b47f-11ea-9748-7197363634a1.png)

**Comment by Misly16** [comment]
Make sure to replace <dbname> with a name and <password> with a valid password, but don't include the <>

**Comment by HaryoPratama** [comment]
yup 
![image](https://user-images.githubusercontent.com/62017665/85285681-d6284b80-b480-11ea-9e3e-82d57d87c8e0.png)

**Comment by HaryoPratama** [comment]
solved, i added ; on index.js
